apiVersion: v1
kind: Service
metadata:
  name: {{ include "motioneye.fullname" . }}
  labels:
    {{- include "motioneye.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: 8765
      protocol: TCP
      name: web
    - port: {{ .Values.service.streamPort }}
      targetPort: 8081
      protocol: TCP
      name: stream
  selector:
    {{- include "motioneye.selectorLabels" . | nindent 4 }}
